# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
